services:

  db:
    image: postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_DB: fancanvas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: .


    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
    - ./static:/app/static

    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:alpine

    restart: unless-stopped

    ports:
      - "3000:80"

    volumes:
      - ./frontend:/usr/share/nginx/html:ro

    depends_on:
      - backend

volumes:
  postgres_data:
